name: flutter_app_base
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.3.0
  connectivity_plus: ^4.0.1
  cupertino_icons: ^1.0.6
  device_info_plus: ^9.1.0
  firebase_analytics: ^10.6.4
  firebase_core: ^2.22.0
  firebase_crashlytics: ^3.4.4
  firebase_messaging: ^14.7.4
  flutter_local_notifications: ^16.1.0
  http: ^0.13.6
  inventiv_critic_flutter: ^0.2.0
  logging: ^1.0.2
  package_info_plus: ^4.2.0
  rxdart: ^0.27.7
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.6
  flutter_lints: ^3.0.1
  mockito: ^5.4.2

flutter:
  uses-material-design: true
  assets:
    - assets/loading.png