name: flutter_app_base
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.2 <4.0.0"

dependencies:
  cached_network_image: ^3.4.1
  connectivity_plus: ^6.1.0
  cupertino_icons: ^1.0.8
  device_info_plus: ^11.1.1
  firebase_analytics: ^10.6.4
  firebase_core: ^2.22.0
  firebase_crashlytics: ^3.4.4
  firebase_messaging: ^14.7.4
  flutter:
    sdk: flutter
  flutter_local_notifications: ^18.0.1
  http: ^1.2.2
  inventiv_critic_flutter: ^0.4.0
  logging: ^1.3.0
  package_info_plus: ^8.1.1
  rxdart: ^0.28.0
  shared_preferences: ^2.3.3

dev_dependencies:
  build_runner: ^2.4.6
  firebase_core_platform_interface: ^5.0.0
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  mockito: ^5.4.2

flutter:
  uses-material-design: true
  assets:
    - assets/loading.png
