# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc 'Submit a new Beta Build to Fastlane'
  lane :staging_firebase do
    raise 'Update your Fastfile to deploy to a different firebase app' if ENV['CI_PROJECT_NAME'] != 'my-awesome-app'

    gradle(task: 'clean assembleRelease')
    firebase_app_distribution(
      app: '1:548746061485:android:71905375df6e53cd450824',
      android_artifact_type: 'APK',
      android_artifact_path: '../build/app/outputs/flutter-apk/app-release.apk',
      release_notes_file: '../CHANGELOG.md',
      groups: 'internal'
    )
  end
end
