name: Increment Build Number
on:
  workflow_dispatch:
  workflow_call:

jobs:
  increment_build_number:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.5.0

      - name: Configure Git
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Increment build number and create a new tag
        run: |
          # Fetch all tags
          git fetch --prune --unshallow --tags

          # Find the latest build number and increment it
          LATEST_BUILD_TAG=$(git tag -l "build-*" | sort -V | tail -n 1)
          LATEST_BUILD_NUM=${LATEST_BUILD_TAG#build-}
          NEW_BUILD_NUM=$((LATEST_BUILD_NUM + 1))

          # Create and push the new build tag
          git tag "build-$NEW_BUILD_NUM" HEAD
          git push origin "build-$NEW_BUILD_NUM"

          # Set the new build number as an output variable for other steps
          echo "BUILD_NUMBER=$NEW_BUILD_NUM" >> $GITHUB_ENV