name: iOS Builds

on:
  workflow_call:
    inputs:
      pilot_apple_id:
        description: 'Apple ID for the app'
        required: true
        type: string
      flavor:
        description: 'Flavor to use'
        required: true
        type: string

jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 30

    env:
      LC_ALL: en_US.UTF-8
      LANG: en_US.UTF-8
      PILOT_USERNAME: admin@twinsunsolutions.com
      PILOT_APP_IDENTIFIER: dev.twinsun.flutter-app-base
      PILOT_TEAM_ID: N/A - There is no value for REPLACE_ME_PILOT_TEAM_ID
      PILOT_DEV_PORTAL_TEAM_ID: N/A - There is no value for REPLACE_ME_DEV_PORTAL_TEAM_ID

      # Inputs
      PILOT_APPLE_ID: ${{ inputs.pilot_apple_id }}
      FLAVOR: ${{ inputs.flavor }}

      # Secrets
      FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}
      KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
      MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}
      MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3.5.0

    - name: Setup Dart
      uses: dart-lang/setup-dart@v1

    # - name: Find Build Number
    #   uses: ./.github/workflows/find_build_number
    #   id: find_build_number

    - name: Set Flutter Version
      run: ./.github/workflows/set_flutter_version
      id: set_flutter_version

    # - name: Initialize Flutter Project
    #   run: |
    #     fvm flutter pub get
    #     pod repo update
    #     fvm flutter clean

    # - name: Deploy iOS Build
    #   run: bin/deploy ios $FLAVOR "${{ steps.find_build_number.outputs.build_number }}" "$BUILD_NAME_OVERRIDE"