name: Tests

on:
  workflow_dispatch:
  workflow_call:
  pull_request:

env:
  LC_ALL: "en_US.UTF-8"
  LANG: "en_US.UTF-8"

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: twinsunllc/flutter
      options: --user root

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3.5.0

      - name: Setup FVM
        run: |
          git config --global --add safe.directory /home/flutter/flutter-sdk
          dart pub global activate fvm
          echo "${HOME}/.pub-cache/bin" >> $GITHUB_PATH

      - name: Set Flutter Version
        run: |
          flutter pub global activate fvm
          fvm install $(cat .fvmrc | jq -r .flutter)
          fvm use $(cat .fvmrc | jq -r .flutter)

      - name: Install Dependencies
        run: fvm flutter pub get

      - name: Generate Mocks
        run: fvm flutter pub run build_runner build --delete-conflicting-outputs

      - name: Run Tests
        run: fvm flutter test
