name: Tests

on:
  workflow_dispatch:
  workflow_call:
  pull_request:

env:
  LC_ALL: "en_US.UTF-8"
  LANG: "en_US.UTF-8"

jobs:
  test:
    runs-on: [runs-on,runner=2cpu-linux-x64,"run-id=${{ github.run_id }}"]
    container:
      image: twinsunllc/flutter
      options: --user root
    steps:
      - uses: actions/checkout@v3.5.0
      - name: Setup FVM
        run: |
          git config --global --add safe.directory /home/flutter/flutter-sdk
          dart pub global activate fvm
          echo "${HOME}/.pub-cache/bin" >> $GITHUB_PATH
      - name: Setup Flutter
        run: |
          fvm install $(cat .flutter-version)
          fvm use $(cat .flutter-version)
      - name: Install dependencies
        run: fvm flutter pub get
      - name: Generate mocks
        run: fvm flutter pub run build_runner build --delete-conflicting-outputs
      - name: Run tests
        run: fvm flutter test
