name: Tests

on:
  workflow_dispatch:
  workflow_call:
  pull_request:

env:
  LC_ALL: "en_US.UTF-8"
  LANG: "en_US.UTF-8"

jobs:
  test:
    runs-on: [runs-on,runner=2cpu-linux-x64,"run-id=${{ github.run_id }}"]
    container:
      image: twinsunllc/flutter
      options: --user root

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3.5.0

      - name: Set Flutter Version
        run: ./.github/scripts/set_flutter_version.sh

      - name: Install Dependencies
        run: fvm flutter pub get

      - name: Generate Mocks
        run: fvm flutter pub run build_runner build --delete-conflicting-outputs

      - name: Run Tests
        run: fvm flutter test
