name: Tests

on:
  workflow_dispatch:
  workflow_call:
  pull_request:
    branches:
      - main

env:
  LC_ALL: "en_US.UTF-8"
  LANG: "en_US.UTF-8"

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: twinsunllc/flutter
      options: --user root
    steps:
    - uses: actions/checkout@v3.5.0
    - run: echo "FLUTTER_VERSION=$(cat .flutter-version)" >> $GITHUB_ENV
    - run: git config --global --add safe.directory /home/flutter/flutter-sdk
    - run: /usr/bin/env /bin/bash -c "cd /home/flutter/flutter-sdk; git fetch origin; git fetch twinsunllc; git checkout $FLUTTER_VERSION && flutter doctor"
    - run: flutter pub get
    - run: flutter test
